version: '3.8'

services:
  web:
    build: php-apache
    volumes:
      - ../:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "${WEB_PORT}:80"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - db
  db:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learn_app
      MYSQL_USER: learn
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "${DB_PORT}:3306"
